In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['Yash', 'Rahul', 'Sneha', 'Amit', 'Pooja',
             'Karan', 'Neha', 'Riya', 'Arjun', 'Priya'],

    'Maths': [85, 90, np.nan, 40, 95,
              200, 76, 88, 92, 35],

    'Science': [78, 85, 89, np.nan, 91,
                87, 300, 84, 79, 60],

    'English': [80, 70, 65, 50, np.nan,
                75, 85, 90, 95, 40],

    'Attendance': [90, 85, 88, 70, 95,
                   92, 89, np.nan, 96, 65]
}

df = pd.DataFrame(data)

print("Original Dataset:")
df

Original Dataset:

    Name  Maths  Science  English  Attendance
0   Yash   85.0     78.0     80.0        90.0
1  Rahul   90.0     85.0     70.0        85.0
2  Sneha    NaN     89.0     65.0        88.0
3   Amit   40.0      NaN     50.0        70.0
4  Pooja   95.0     91.0      NaN        95.0
5  Karan  200.0     87.0     75.0        92.0
6   Neha   76.0    300.0     85.0        89.0
7   Riya   88.0     84.0     90.0         NaN
8  Arjun   92.0     79.0     95.0        96.0
9  Priya   35.0     60.0     40.0        65.0

In [3]:
print("Missing Values in Dataset:\n")

print(df.isnull().sum())

Missing Values in Dataset:

Name          0
Maths         1
Science       1
English       1
Attendance    1
dtype: int64

In [4]:
df['Maths'] = df['Maths'].fillna(df['Maths'].mean())

df['Science'] = df['Science'].fillna(df['Science'].mean())

df['English'] = df['English'].fillna(df['English'].mean())

df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())

print("Dataset After Handling Missing Values:")
df

Dataset After Handling Missing Values:

    Name  Maths     Science    English  Attendance
0   Yash   85.0   78.000000  80.000000   90.000000
1  Rahul   90.0   85.000000  70.000000   85.000000
2  Sneha   89.0   89.000000  65.000000   88.000000
3   Amit   40.0  105.888889  50.000000   70.000000
4  Pooja   95.0   91.000000  72.222222   95.000000
5  Karan  200.0   87.000000  75.000000   92.000000
6   Neha   76.0  300.000000  85.000000   89.000000
7   Riya   88.0   84.000000  90.000000   85.555556
8  Arjun   92.0   79.000000  95.000000   96.000000
9  Priya   35.0   60.000000  40.000000   65.000000

In [5]:
df.loc[df['Maths'] > 100, 'Maths'] = df['Maths'].mean()

df.loc[df['Science'] > 100, 'Science'] = df['Science'].mean()

print("Dataset After Handling Inconsistencies:")
df

Dataset After Handling Inconsistencies:

    Name  Maths     Science    English  Attendance
0   Yash   85.0   78.000000  80.000000   90.000000
1  Rahul   90.0   85.000000  70.000000   85.000000
2  Sneha   89.0   89.000000  65.000000   88.000000
3   Amit   40.0  105.888889  50.000000   70.000000
4  Pooja   95.0   91.000000  72.222222   95.000000
5  Karan   89.0   87.000000  75.000000   92.000000
6   Neha   76.0  105.888889  85.000000   89.000000
7   Riya   88.0   84.000000  90.000000   85.555556
8  Arjun   92.0   79.000000  95.000000   96.000000
9  Priya   35.0   60.000000  40.000000   65.000000

In [6]:
Q1 = df['Maths'].quantile(0.25)

Q3 = df['Maths'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR

upper = Q3 + 1.5 * IQR

print("Lower Limit:", lower)

print("Upper Limit:", upper)

Lower Limit: 61.0
Upper Limit: 107.0

In [7]:
df = df[
    (df['Maths'] >= lower) &
    (df['Maths'] <= upper)
]

print("Dataset After Removing Outliers:")
df

Dataset After Removing Outliers:

    Name  Maths     Science    English  Attendance
0   Yash   85.0   78.000000  80.000000   90.000000
1  Rahul   90.0   85.000000  70.000000   85.000000
2  Sneha   89.0   89.000000  65.000000   88.000000
4  Pooja   95.0   91.000000  72.222222   95.000000
5  Karan   89.0   87.000000  75.000000   92.000000
6   Neha   76.0  105.888889  85.000000   89.000000
7   Riya   88.0   84.000000  90.000000   85.555556
8  Arjun   92.0   79.000000  95.000000   96.000000

In [ ]:
df['Maths'] = (
    (df['Maths'] - df['Maths'].min())
    /
    (df['Maths'].max() - df['Maths'].min())
)

print("Dataset After Normalization:")
df